### ISSUE TITLE
simpsons.txt has non-English words and additional bugs

### ISSUE THREAD

**Issue by atoponce** [PeerioTechnologies/peerio-web-passphrase-generator#1]
Noticed entries in the simpsons.txt word list that probably shouldn't be there:

    wwwopensubtitlesorg
    {yi}singing
    ¶
    Â¶
    -g

**Comment by faust64** [comment]
Hi,

Thanks for reporting this.
Fixing right now.

Best regards.

**Comment by atoponce** [comment]
Will the words be replaced bringing the size of the dictionary back up to 5,000 words, or just left at 4,996?

**Comment by faust64** [comment]
Sure, why not
