### ISSUE TITLE
simpsons.txt contains spurious characters at the beginning and end of some words

### ISSUE THREAD

**Issue by atoponce** [PeerioTechnologies/peerio-web-passphrase-generator#2]
Using the following commands on simpsons.txt, shows the line numbers that have words with spurious characters at the beginning and end of each word. The full search:

    $ grep -n -E '(^[[:punct:]]+|[[:punct:]]+$)' simpsons.txt
    375:'em
    417:'cause
    1134:&
    1192:o/
    1306:nothin'
    1325:goin'
    1329:''
    1406:'
    1465:doin'
    1656:'bout
    1804:gettin'
    1859:''i
    2022:you|
    2023:lookin'
    2110:talkin'
    2301:comin'
    2367:homer|
    2412:somethin'
    2567:ol'
    2635:''the
    2640:'tis
    2705:burns'
    2843:it|
    2969:man|
    3202:'t
    3261:kids'
    3321:dad|
    3338:'60s
    3495:me|
    3550:'n'
    3632:not|
    3652:sir|
    3855:bart|
    3877:girls'
    3974:flanders'
    4074:off|
    4122:here|
    4128:workin'
    4133:freakin'
    4318:mom|
    4365:what|
    4544:right|
    4555:yeah|
    4625:marge|
    4663:no|
    4718:it''
    4759:do|
    4788:100%

The problematic words are:

* ones that end with the vertical bar `|`
* line 1859 with `''i`
* line 1192 with `o/`
* line 2635 with `''the`
* line 4718 with `it''`

Lines 3202 and 3550 are also questionable. Fixing those words, sorting, and uniqifying the word list removes 23 entries, leaving the list at 4,977 unique words. Thus, 23 additional words should be supplied bringing the word list back up to 5,000 unique entries.

**Comment by atoponce** [comment]
Here is my sorted and uniqified simpsons.txt with 4,777 entries: https://ae7.st/p/7zm

**Comment by faust64** [comment]
Thanks for your report.
These should be fixed. Let me know if you find anything else.

Regards.
