### ISSUE TITLE
simpsons.txt contains the word "you|to"

### ISSUE THREAD

**Issue by atoponce** [PeerioTechnologies/peerio-web-passphrase-generator#3]
The word "you|to" on line 4617 of the simpsons.txt word list is a spurious entry with the vertical bar. I'm guessing it was meant to be two words "you" and "to", which already exist in the word list. A new word should probably replace it.

**Comment by atoponce** [comment]
So I guess Peerio is no longer, which means that probably no one is watching this project any longer. So, I suggest "peerio" as the replacement. It is also six characters, and is homage to the company that created it.

I'll keep this issue open should any former staffer swing by.

**Comment by anri-asaturov** [comment]
I do watch it

**Comment by anri-asaturov** [comment]
If you make a PR I will merge it, otherwise I can get to it in the next few days

**Comment by atoponce** [comment]
Thanks!
